<?php
/**
 * Database Setup Wizard - Automatic Hosting Platform Detection
 * Automatically configures database connection for any hosting platform
 */

require_once 'config.php';

// Auto-detect and configure database
function autoConfigureDatabase() {
    $results = [];
    
    // Test all possible configurations
    $configs = getAllDatabaseConfigs();
    
    foreach ($configs as $name => $config) {
        $result = testDatabaseConfig($config);
        $results[$name] = array_merge($result, ['config' => $config]);
        
        // If we find a working connection, stop testing
        if ($result['success']) {
            return [
                'success' => true,
                'working_config' => $config,
                'config_name' => $name,
                'all_results' => $results
            ];
        }
    }
    
    return [
        'success' => false,
        'working_config' => null,
        'all_results' => $results
    ];
}

// Get all possible database configurations
function getAllDatabaseConfigs() {
    return [
        'Shared Hosting (cPanel)' => [
            'host' => 'localhost',
            'user' => 'salem_admin',
            'pass' => '',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ],
        'Shared Hosting (Root)' => [
            'host' => 'localhost',
            'user' => 'root',
            'pass' => '',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ],
        'Shared Hosting (With Password)' => [
            'host' => 'localhost',
            'user' => 'salem_admin',
            'pass' => 'password',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ],
        'VPS/Dedicated (127.0.0.1)' => [
            'host' => '127.0.0.1',
            'user' => 'salem_admin',
            'pass' => '',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ],
        'Cloud Hosting (Environment)' => [
            'host' => $_ENV['DB_HOST'] ?? 'localhost',
            'user' => $_ENV['DB_USER'] ?? 'salem_admin',
            'pass' => $_ENV['DB_PASS'] ?? '',
            'name' => $_ENV['DB_NAME'] ?? 'salem_dominion_ministries',
            'port' => $_ENV['DB_PORT'] ?? 3306
        ],
        'Custom Configuration' => [
            'host' => DB_HOST,
            'user' => DB_USER,
            'pass' => DB_PASS,
            'name' => DB_NAME,
            'port' => DB_PORT
        ],
        'Emergency Config 1' => [
            'host' => 'localhost',
            'user' => 'salem_admin',
            'pass' => '123456',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ],
        'Emergency Config 2' => [
            'host' => 'localhost',
            'user' => 'root',
            'pass' => 'root',
            'name' => 'salem_dominion_ministries',
            'port' => 3306
        ]
    ];
}

// Test database configuration
function testDatabaseConfig($config) {
    try {
        $conn = new mysqli(
            $config['host'],
            $config['user'],
            $config['pass'],
            $config['name'],
            $config['port']
        );
        
        if ($conn->connect_error) {
            return [
                'success' => false,
                'error' => $conn->connect_error
            ];
        }
        
        // Test database access
        $queries = [
            "SELECT 1",
            "SHOW TABLES",
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '" . $config['name'] . "'"
        ];
        
        foreach ($queries as $query) {
            $result = $conn->query($query);
            if (!$result) {
                $conn->close();
                return [
                    'success' => false,
                    'error' => 'Database query failed: ' . $query
                ];
            }
        }
        
        $conn->close();
        return [
            'success' => true,
            'message' => 'Connection successful!'
        ];
    } catch (Exception $e) {
        return [
            'success' => false,
            'error' => $e->getMessage()
        ];
    }
}

// Update config.php with working configuration
function updateConfigFile($working_config) {
    $config_content = "<?php\n";
    $config_content .= "/**\n";
    $config_content .= " * Database Configuration - Auto-Generated by Database Wizard\n";
    $config_content .= " * Generated on: " . date('Y-m-d H:i:s') . "\n";
    $config_content .= " */\n\n";
    
    $config_content .= "// Database Configuration - Working Configuration\n";
    $config_content .= "define('DB_HOST', '" . $working_config['host'] . "');\n";
    $config_content .= "define('DB_USER', '" . $working_config['user'] . "');\n";
    $config_content .= "define('DB_PASS', '" . $working_config['pass'] . "');\n";
    $config_content .= "define('DB_NAME', '" . $working_config['name'] . "');\n";
    $config_content .= "define('DB_PORT', " . $working_config['port'] . ");\n\n";
    
    // Add church branding
    $config_content .= "// Church Branding\n";
    $config_content .= "define('CHURCH_NAME', '" . CHURCH_NAME . "');\n";
    $config_content .= "define('CHURCH_LOGO', '" . CHURCH_LOGO . "');\n";
    $config_content .= "define('CHURCH_PASTOR', '" . CHURCH_PASTOR . "');\n";
    
    // Dynamic website URL
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $config_content .= "define('CHURCH_WEBSITE', '" . $protocol . "://" . $host . "');\n";
    $config_content .= "define('CHURCH_DESCRIPTION', '" . CHURCH_DESCRIPTION . "');\n\n";
    
    // Add other configurations
    $config_content .= "// Upload Configuration\n";
    $config_content .= "define('UPLOAD_PATH', 'uploads/');\n";
    $config_content .= "define('MAX_FILE_SIZE', 50 * 1024 * 1024); // 50MB\n\n";
    
    $config_content .= "// Email Configuration\n";
    $config_content .= "define('ADMIN_EMAIL', 'admin@salem-church.org');\n";
    $config_content .= "define('CHURCH_EMAIL', 'info@salem-church.org');\n\n";
    
    $config_content .= "// Security\n";
    $config_content .= "define('SECURE_COOKIES', true);\n";
    $config_content .= "define('SESSION_LIFETIME', 7200); // 2 hours\n";
    
    return file_put_contents('config.php', $config_content) !== false;
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    if ($_POST['action'] === 'auto_configure') {
        $result = autoConfigureDatabase();
        
        if ($result['success']) {
            // Update config file with working configuration
            $updated = updateConfigFile($result['working_config']);
            
            echo json_encode([
                'success' => true,
                'message' => 'Database configured successfully!',
                'config_name' => $result['config_name'],
                'config_updated' => $updated,
                'working_config' => $result['working_config']
            ]);
        } else {
            echo json_encode([
                'success' => false,
                'message' => 'No working database configuration found',
                'all_results' => $result['all_results']
            ]);
        }
        exit;
    }
    
    if ($_POST['action'] === 'test_config') {
        $config = [
            'host' => $_POST['host'],
            'user' => $_POST['user'],
            'pass' => $_POST['pass'],
            'name' => $_POST['name'],
            'port' => intval($_POST['port'])
        ];
        
        $result = testDatabaseConfig($config);
        echo json_encode($result);
        exit;
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup Wizard - <?php echo CHURCH_NAME; ?></title>
    
    <!-- Church Branding -->
    <link rel="icon" type="image/jpeg" href="<?php echo CHURCH_LOGO; ?>">
    
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            color: #333;
        }
        
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
        }
        
        .wizard-card {
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            margin-bottom: 20px;
        }
        
        .wizard-header {
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .wizard-header .logo {
            width: 80px;
            height: 80px;
            margin-bottom: 20px;
            border-radius: 50%;
            border: 3px solid #fbbf24;
        }
        
        .wizard-header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
            font-weight: 700;
        }
        
        .wizard-header p {
            font-size: 1.1em;
            opacity: 0.9;
        }
        
        .wizard-content {
            padding: 40px;
        }
        
        .section-title {
            font-size: 1.8em;
            color: #0f172a;
            margin-bottom: 20px;
            font-weight: 600;
        }
        
        .btn {
            background: linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%);
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 8px;
            cursor: pointer;
            font-size: 1.1em;
            font-weight: 600;
            transition: all 0.3s ease;
            margin: 10px 0;
        }
        
        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(14, 165, 233, 0.3);
        }
        
        .btn-success {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        }
        
        .btn-danger {
            background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
        }
        
        .status-message {
            padding: 20px;
            border-radius: 10px;
            margin: 20px 0;
            font-weight: 500;
        }
        
        .status-success {
            background: #10b981;
            color: white;
            border: 1px solid #059669;
        }
        
        .status-error {
            background: #ef4444;
            color: white;
            border: 1px solid #dc2626;
        }
        
        .status-info {
            background: #3b82f6;
            color: white;
            border: 1px solid #2563eb;
        }
        
        .loading {
            display: inline-block;
            width: 20px;
            height: 20px;
            border: 3px solid rgba(255, 255, 255, 0.3);
            border-radius: 50%;
            border-top-color: white;
            animation: spin 1s ease-in-out infinite;
        }
        
        @keyframes spin {
            to { transform: rotate(360deg); }
        }
        
        .config-form {
            background: #f8fafc;
            padding: 30px;
            border-radius: 10px;
            margin: 20px 0;
        }
        
        .form-group {
            margin-bottom: 20px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
            color: #374151;
        }
        
        .form-group input {
            width: 100%;
            padding: 12px;
            border: 1px solid #d1d5db;
            border-radius: 6px;
            font-size: 1em;
        }
        
        .form-group input:focus {
            outline: none;
            border-color: #0ea5e9;
            box-shadow: 0 0 0 3px rgba(14, 165, 233, 0.1);
        }
        
        .form-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }
        
        .result-item {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin: 10px 0;
            border-left: 4px solid #d1d5db;
        }
        
        .result-item.success {
            border-left-color: #10b981;
            background: #f0fdf4;
        }
        
        .result-item.error {
            border-left-color: #ef4444;
            background: #fef2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="wizard-card">
            <div class="wizard-header">
                <img src="<?php echo CHURCH_LOGO; ?>" alt="<?php echo CHURCH_NAME; ?>" class="logo">
                <h1>Database Setup Wizard</h1>
                <p>Automatic database configuration for your hosting platform</p>
            </div>
            
            <div class="wizard-content">
                <h2 class="section-title">Automatic Database Configuration</h2>
                <p style="margin-bottom: 30px; color: #6b7280;">
                    Click the button below to automatically detect and configure your database connection. 
                    This wizard will test multiple configurations and find the one that works for your hosting platform.
                </p>
                
                <button class="btn" onclick="autoConfigureDatabase()">
                    <span id="auto-btn-text">Auto-Configure Database</span>
                    <span id="auto-loading" class="loading" style="display: none;"></span>
                </button>
                
                <div id="auto-result"></div>
                
                <div class="config-form" style="margin-top: 40px;">
                    <h3 style="margin-bottom: 20px;">Manual Database Configuration</h3>
                    <p style="margin-bottom: 20px; color: #6b7280;">
                        If auto-configuration doesn't work, you can manually test your database credentials:
                    </p>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label>Database Host</label>
                            <input type="text" id="manual-host" value="localhost" placeholder="localhost">
                        </div>
                        <div class="form-group">
                            <label>Database Port</label>
                            <input type="number" id="manual-port" value="3306" placeholder="3306">
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label>Database User</label>
                            <input type="text" id="manual-user" value="salem_admin" placeholder="username">
                        </div>
                        <div class="form-group">
                            <label>Database Password</label>
                            <input type="password" id="manual-pass" placeholder="password">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label>Database Name</label>
                        <input type="text" id="manual-name" value="salem_dominion_ministries" placeholder="database_name">
                    </div>
                    
                    <button class="btn" onclick="testManualConfig()">Test Manual Configuration</button>
                    <div id="manual-result"></div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        function autoConfigureDatabase() {
            const btn = document.querySelector('.btn');
            const btnText = document.getElementById('auto-btn-text');
            const loading = document.getElementById('auto-loading');
            const result = document.getElementById('auto-result');
            
            btnText.textContent = 'Configuring...';
            loading.style.display = 'inline-block';
            btn.disabled = true;
            result.innerHTML = '';
            
            fetch('database_wizard.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: new URLSearchParams({
                    action: 'auto_configure'
                })
            })
            .then(response => response.json())
            .then(data => {
                btnText.textContent = 'Auto-Configure Database';
                loading.style.display = 'none';
                btn.disabled = false;
                
                if (data.success) {
                    result.innerHTML = `
                        <div class="status-message status-success">
                            <h3>Database Configured Successfully!</h3>
                            <p><strong>Configuration Used:</strong> ${data.config_name}</p>
                            <p><strong>Config File Updated:</strong> ${data.config_updated ? 'Yes' : 'No'}</p>
                            <p>Your database is now online and working perfectly!</p>
                            <a href="admin_dashboard.php" class="btn btn-success" style="margin-top: 15px;">Go to Admin Dashboard</a>
                        </div>
                    `;
                } else {
                    let errorHtml = `
                        <div class="status-message status-error">
                            <h3>Database Configuration Failed</h3>
                            <p>No working database configuration was found. Please check your hosting provider's database settings.</p>
                            <h4>Test Results:</h4>
                    `;
                    
                    for (const [name, result] of Object.entries(data.all_results)) {
                        errorHtml += `
                            <div class="result-item ${result.success ? 'success' : 'error'}">
                                <strong>${name}:</strong> ${result.success ? 'Success' : 'Failed - ' + result.error}
                            </div>
                        `;
                    }
                    
                    errorHtml += '</div>';
                    result.innerHTML = errorHtml;
                }
            })
            .catch(error => {
                btnText.textContent = 'Auto-Configure Database';
                loading.style.display = 'none';
                btn.disabled = false;
                result.innerHTML = `
                    <div class="status-message status-error">
                        <h3>Configuration Error</h3>
                        <p>An error occurred: ${error.message}</p>
                    </div>
                `;
            });
        }
        
        function testManualConfig() {
            const config = {
                host: document.getElementById('manual-host').value,
                port: document.getElementById('manual-port').value,
                user: document.getElementById('manual-user').value,
                pass: document.getElementById('manual-pass').value,
                name: document.getElementById('manual-name').value
            };
            
            const result = document.getElementById('manual-result');
            result.innerHTML = '<div class="status-message status-info">Testing database connection...</div>';
            
            fetch('database_wizard.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: new URLSearchParams({
                    action: 'test_config',
                    ...config
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    result.innerHTML = `
                        <div class="status-message status-success">
                            <h3>Connection Successful!</h3>
                            <p>Your database configuration is working perfectly.</p>
                            <p>Please update your config.php file with these credentials.</p>
                        </div>
                    `;
                } else {
                    result.innerHTML = `
                        <div class="status-message status-error">
                            <h3>Connection Failed</h3>
                            <p>Error: ${data.error}</p>
                            <p>Please check your database credentials and try again.</p>
                        </div>
                    `;
                }
            })
            .catch(error => {
                result.innerHTML = `
                    <div class="status-message status-error">
                        <h3>Test Error</h3>
                        <p>An error occurred: ${error.message}</p>
                    </div>
                `;
            });
        }
    </script>
</body>
</html>
