<?php
// DATABASE SETUP WIZARD - Salem Dominion Ministries
// Comprehensive database configuration and testing tool

session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup Wizard - Salem Dominion Ministries</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; }
        .wizard-container { max-width: 900px; margin: 50px auto; }
        .card { border: none; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
        .card-header { background: linear-gradient(45deg, #667eea, #764ba2); border-radius: 15px 15px 0 0; }
        .btn-primary { background: linear-gradient(45deg, #667eea, #764ba2); border: none; }
        .status-indicator { width: 12px; height: 12px; border-radius: 50%; display: inline-block; margin-right: 8px; }
        .status-success { background-color: #28a745; }
        .status-error { background-color: #dc3545; }
        .status-warning { background-color: #ffc107; }
        .config-section { margin-bottom: 25px; padding: 20px; border: 1px solid #e9ecef; border-radius: 8px; background-color: #f8f9fa; }
        .test-result { padding: 15px; border-radius: 8px; margin: 10px 0; }
    </style>
</head>
<body>
    <div class="wizard-container">
        <div class="card">
            <div class="card-header text-white text-center py-3">
                <h3><i class="fas fa-database me-2"></i>Database Setup Wizard</h3>
                <p class="mb-0">Configure your database connection for hosting platform</p>
            </div>
            <div class="card-body p-4">
                <?php
                $message = '';
                $connection_status = 'unknown';
                
                if ($_POST) {
                    // Get form data
                    $host = $_POST['host'] ?? 'localhost';
                    $user = $_POST['user'] ?? 'root';
                    $pass = $_POST['pass'] ?? '';
                    $name = $_POST['name'] ?? 'salem_dominion_ministries';
                    $port = $_POST['port'] ?? '3306';
                    
                    // Test connection
                    try {
                        $conn = new mysqli($host, $user, $pass, $name, $port);
                        if ($conn->connect_error) {
                            $message = '<div class="alert alert-danger"><i class="fas fa-exclamation-triangle me-2"></i>Connection failed: ' . htmlspecialchars($conn->connect_error) . '</div>';
                            $connection_status = 'error';
                        } else {
                            // Test database access
                            $test_result = $conn->query("SELECT 1");
                            if ($test_result) {
                                $message = '<div class="alert alert-success"><i class="fas fa-check-circle me-2"></i>Database connection successful!</div>';
                                $connection_status = 'success';
                                
                                // Update db_connection.php with working configuration
                                updateDatabaseConnection($host, $user, $pass, $name, $port);
                            } else {
                                $message = '<div class="alert alert-warning"><i class="fas fa-exclamation-triangle me-2"></i>Connected but database access failed. Check database permissions.</div>';
                                $connection_status = 'warning';
                            }
                            $conn->close();
                        }
                    } catch (Exception $e) {
                        $message = '<div class="alert alert-danger"><i class="fas fa-exclamation-triangle me-2"></i>Error: ' . htmlspecialchars($e->getMessage()) . '</div>';
                        $connection_status = 'error';
                    }
                }
                
                function updateDatabaseConnection($host, $user, $pass, $name, $port) {
                    $config_content = "<?php\n";
                    $config_content .= "// Database configuration for hosting platform\n";
                    $config_content .= "// Generated by Database Setup Wizard on " . date('Y-m-d H:i:s') . "\n\n";
                    $config_content .= "// Hosting platform database connection\n";
                    $config_content .= "function getHostingDatabaseConnection() {\n";
                    $config_content .= "    try {\n";
                    $config_content .= "        return new mysqli('$host', '$user', '$pass', '$name', $port);\n";
                    $config_content .= "    } catch (Exception \$e) {\n";
                    $config_content .= "        error_log('Database connection error: ' . \$e->getMessage());\n";
                    $config_content .= "        return null;\n";
                    $config_content .= "    }\n";
                    $config_content .= "}\n";
                    
                    file_put_contents('db_hosting_config.php', $config_content);
                }
                ?>
                
                <?php if ($message): ?>
                    <?php echo $message; ?>
                <?php endif; ?>
                
                <form method="POST" class="needs-validation" novalidate>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="config-section">
                                <h5><i class="fas fa-server me-2"></i>Database Server</h5>
                                <div class="mb-3">
                                    <label for="host" class="form-label">Database Host</label>
                                    <input type="text" class="form-control" id="host" name="host" 
                                           value="<?php echo htmlspecialchars($_POST['host'] ?? 'localhost'); ?>" required>
                                    <div class="form-text">Common hosting hosts: localhost, 127.0.0.1, or your hosting provider's database server</div>
                                </div>
                                
                                <div class="mb-3">
                                    <label for="port" class="form-label">Port</label>
                                    <input type="number" class="form-control" id="port" name="port" 
                                           value="<?php echo htmlspecialchars($_POST['port'] ?? '3306'); ?>" required>
                                    <div class="form-text">Default MySQL port is 3306</div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="config-section">
                                <h5><i class="fas fa-user me-2"></i>Database Credentials</h5>
                                <div class="mb-3">
                                    <label for="user" class="form-label">Username</label>
                                    <input type="text" class="form-control" id="user" name="user" 
                                           value="<?php echo htmlspecialchars($_POST['user'] ?? 'root'); ?>" required>
                                </div>
                                
                                <div class="mb-3">
                                    <label for="pass" class="form-label">Password</label>
                                    <input type="password" class="form-control" id="pass" name="pass" 
                                           value="<?php echo htmlspecialchars($_POST['pass'] ?? ''); ?>">
                                    <div class="form-text">Leave empty if no password is set</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="config-section">
                                <h5><i class="fas fa-database me-2"></i>Database Name</h5>
                                <div class="mb-3">
                                    <label for="name" class="form-label">Database Name</label>
                                    <input type="text" class="form-control" id="name" name="name" 
                                           value="<?php echo htmlspecialchars($_POST['name'] ?? 'salem_dominion_ministries'); ?>" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row mt-4">
                        <div class="col-12 text-center">
                            <button type="submit" class="btn btn-primary btn-lg px-5">
                                <i class="fas fa-plug me-2"></i>Test Connection
                            </button>
                        </div>
                    </div>
                </form>
                
                <?php if ($connection_status === 'success'): ?>
                <div class="test-result bg-success text-white">
                    <h5><i class="fas fa-check-circle me-2"></i>Configuration Saved!</h5>
                    <p>Your database connection has been configured and saved to <code>db_hosting_config.php</code></p>
                    <p><strong>Next Steps:</strong></p>
                    <ol>
                        <li>Upload this file to your hosting platform</li>
                        <li>Test your admin dashboard</li>
                        <li>If issues persist, contact your hosting provider for database details</li>
                    </ol>
                </div>
                <?php endif; ?>
                
                <div class="mt-4">
                    <h5><i class="fas fa-info-circle me-2"></i>Common Hosting Platform Issues</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Database Host Differences:</h6>
                            <ul>
                                <li><strong>Localhost:</strong> Works on XAMPP/WAMP</li>
                                <li><strong>Hosting:</strong> Usually different hostname</li>
                                <li><strong>Common hosts:</strong> mysql.yourdomain.com, localhost, IP address</li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <h6>Database Credentials:</h6>
                            <ul>
                                <li><strong>Username:</strong> Often different from 'root'</li>
                                <li><strong>Password:</strong> Usually required on hosting</li>
                                <li><strong>Database Name:</strong> May include prefix</li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="text-center mt-4">
                    <a href="admin_dashboard.php" class="btn btn-outline-secondary">
                        <i class="fas fa-arrow-left me-2"></i>Back to Dashboard
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
