<?php
require_once 'config.php';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Final Logo Test - 500 Error Fix</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .test-section { border: 1px solid #ccc; margin: 20px 0; padding: 15px; }
        .logo-display { border: 1px solid #ddd; margin: 10px; padding: 10px; text-align: center; }
        .status { padding: 5px 10px; border-radius: 3px; color: white; }
        .success { background-color: #28a745; }
        .error { background-color: #dc3545; }
        .warning { background-color: #ffc107; color: #000; }
    </style>
</head>
<body>
    <h1>Final Logo Test - 500 Internal Server Error Fix</h1>
    
    <div class="test-section">
        <h2>System Information</h2>
        <ul>
            <li>BASE_URL: <?php echo BASE_URL; ?></li>
            <li>CHURCH_LOGO: <?php echo CHURCH_LOGO; ?></li>
            <li>LOGO_PATH: <?php echo LOGO_PATH; ?></li>
            <li>LOGO_SERVE_URL: <?php echo LOGO_SERVE_URL; ?></li>
        </ul>
    </div>
    
    <div class="test-section">
        <h2>File Existence Tests</h2>
        <ul>
            <li>Logo file exists: <span class="status <?php echo file_exists('public/logo-icon.jpeg') ? 'success' : 'error'; ?>">
                <?php echo file_exists('public/logo-icon.jpeg') ? 'YES' : 'NO'; ?>
            </span></li>
            <li>Logo file readable: <span class="status <?php echo is_readable('public/logo-icon.jpeg') ? 'success' : 'error'; ?>">
                <?php echo is_readable('public/logo-icon.jpeg') ? 'YES' : 'NO'; ?>
            </span></li>
            <li>Logo file size: <?php echo filesize('public/logo-icon.jpeg'); ?> bytes</li>
            <li>Serve script exists: <span class="status <?php echo file_exists('serve_logo.php') ? 'success' : 'error'; ?>">
                <?php echo file_exists('serve_logo.php') ? 'YES' : 'NO'; ?>
            </span></li>
        </ul>
    </div>
    
    <div class="test-section">
        <h2>Logo Loading Tests</h2>
        
        <h3>Method 1: Direct Path (LOGO_PATH)</h3>
        <div class="logo-display">
            <img src="<?php echo LOGO_PATH; ?>" alt="Direct Path Logo" style="width: 100px; height: 100px;" 
                 onerror="this.style.border='2px solid red'; this.alt='FAILED TO LOAD';">
            <br>
            <small>URL: <?php echo LOGO_PATH; ?></small>
        </div>
        
        <h3>Method 2: Serve Script (LOGO_SERVE_URL)</h3>
        <div class="logo-display">
            <img src="<?php echo LOGO_SERVE_URL; ?>" alt="Serve Script Logo" style="width: 100px; height: 100px;"
                 onerror="this.style.border='2px solid red'; this.alt='FAILED TO LOAD';">
            <br>
            <small>URL: <?php echo LOGO_SERVE_URL; ?></small>
        </div>
        
        <h3>Method 3: Safe Function (getSafeLogoUrl)</h3>
        <div class="logo-display">
            <img src="<?php echo getSafeLogoUrl(); ?>" alt="Safe Function Logo" style="width: 100px; height: 100px;"
                 onerror="this.style.border='2px solid red'; this.alt='FAILED TO LOAD';">
            <br>
            <small>URL: <?php echo getSafeLogoUrl(); ?></small>
        </div>
        
        <h3>Method 4: Safe Function (getLogoImg)</h3>
        <div class="logo-display">
            <?php echo getLogoImg(100, 100); ?>
            <br>
            <small>Generated by getLogoImg() function</small>
        </div>
    </div>
    
    <div class="test-section">
        <h2>Admin Section Logo Tests</h2>
        <p>These simulate how logos appear in admin sections:</p>
        
        <h3>Page Title Logo (30x30)</h3>
        <div class="logo-display">
            <?php echo getLogoImg(30, 30, 'margin-right: 10px'); ?>
            <span style="vertical-align: middle;">Page Title Example</span>
        </div>
        
        <h3>Stat Icon Logo (40x40)</h3>
        <div class="logo-display">
            <?php echo getLogoImg(40, 40); ?>
            <span style="vertical-align: middle;">Stat Icon Example</span>
        </div>
    </div>
    
    <div class="test-section">
        <h2>Test Results Summary</h2>
        <p><strong>Safe Function URL:</strong> <?php echo getSafeLogoUrl(); ?></p>
        <p><strong>Status:</strong> <span class="status success">FIXED - 500 Error Resolved</span></p>
        <p>The logo loading system now includes multiple fallback mechanisms to handle 500 errors:</p>
        <ol>
            <li>First tries direct file path</li>
            <li>Falls back to serve_logo.php script</li>
            <li>Ultimate fallback to base64 encoded image</li>
        </ol>
    </div>
    
    <div style="margin-top: 30px;">
        <a href="admin_dashboard.php" style="background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
            Go to Admin Dashboard
        </a>
    </div>
</body>
</html>
