<!DOCTYPE html>
<html>
<head>
    <title>Simple Logo Test - 500 Error Fix</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .test-box { border: 1px solid #ccc; margin: 10px; padding: 15px; text-align: center; }
        .success { border-color: #28a745; background-color: #d4edda; }
        .error { border-color: #dc3545; background-color: #f8d7da; }
        img { border: 1px solid #ddd; margin: 10px; }
    </style>
</head>
<body>
    <h1>Logo 500 Error Fix Test</h1>
    
    <div class="test-box">
        <h3>Test 1: Direct Path (Causes 500)</h3>
        <img src="/public/logo-icon.jpeg" alt="Direct Path" onerror="this.parentElement.classList.add('error')">
        <br><small>URL: /public/logo-icon.jpeg</small>
    </div>
    
    <div class="test-box">
        <h3>Test 2: Logo PHP Script (Should Work)</h3>
        <img src="/logo.php" alt="Logo Script" onerror="this.parentElement.classList.add('error')">
        <br><small>URL: /logo.php</small>
    </div>
    
    <div class="test-box">
        <h3>Test 3: Serve Logo Script (Should Work)</h3>
        <img src="/serve_logo.php" alt="Serve Script" onerror="this.parentElement.classList.add('error')">
        <br><small>URL: /serve_logo.php</small>
    </div>
    
    <div class="test-box">
        <h3>Test 4: Base64 Fallback (Always Works)</h3>
        <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwA/8A8A" alt="Base64">
        <br><small>Base64 encoded (always works)</small>
    </div>
    
    <div class="test-box">
        <h3>Test 5: Admin Section Function</h3>
        <?php require_once 'admin_sections/logo_config.php'; ?>
        <?php echo getAdminLogoImg(100, 100); ?>
        <br><small>Generated by getAdminLogoImg()</small>
    </div>
    
    <div style="margin-top: 30px;">
        <a href="admin_dashboard.php" style="background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
            Test Admin Dashboard
        </a>
    </div>
    
    <script>
        // Add success class to loaded images
        document.querySelectorAll('img').forEach(img => {
            if (img.complete && img.naturalHeight !== 0) {
                img.parentElement.classList.add('success');
            }
        });
    </script>
</body>
</html>
